before_script:
 - conda install dill

stages:
 - test

unittest: # Name of the job
  stage: test
  image: sphiredevel/sphire-ut:latest # Image that should be used
  script:
     - source activate sphire;
     - conda install dill
     - pip uninstall sphire -y;
     - rm -rf build_test
     - cd ..
     - rm -rf build_test
     - pwd;
     - ls;
     - mkdir build_test;
     - cd build_test;
     - cmake /builds/mpi-dortmund/sphire/eman2mirror -DENABLE_OPTIMIZE_MACHINE=ON;
     - make -j 8;
     - make install;
     - cd ..;
     - cd eman2mirror;
     - cd sphire;
     - python setup.py sdist;
     - pip install dist/*.tar.gz;
     - pip install coverage pytest pytest-cov;
     - pip install mrcfile
     - rm -rf resources_tests/applications_folder
     - mkdir resources_tests/applications_folder
     - chmod -R 755 bin_py3/
     - pytest -v tests_bin --cov=sphire/; coverage xml --ignore-errors;
     - mpirun --allow-run-as-root -quiet -np 1 pytest -v tests --cov=sphire/; coverage xml --ignore-errors;
     - rm -rf resources_tests/applications_folder
     - ls
     - pwd
     - cd ../..;
     - rm -rf build_test;

#mpirun --allow-run-as-root -np 1 pytest -v tests --cov=sphire/; coverage xml --ignore-errors;