before_script:
 - apt-get update --yes
 - apt-get install --yes make
 - apt-get install -y build-essential
 - apt-get install libgl1-mesa-dev --yes

stages:
 - test

unittest: # Name of the job
  stage: test
  image: sphiredevel/sphire-ut:eman24 # Image that should be used
  script:
     - source activate sphire;
     - pip uninstall sphire -y;
     - rm -rf build_test
     - cd ..
     - rm -rf build_test
     - pwd;
     - ls;
     - mkdir build_test;
     - cd build_test;
     - cmake /builds/mpi-dortmund/sphire/eman2mirror -DENABLE_OPTIMIZE_MACHINE=ON;
     - make -j 8;
     - make install;
     - cd ..;
     - cd eman2mirror;
     - cd sphire/;
     - python setup.py sdist; pip install dist/*.tar.gz; pip install coverage pytest pytest-cov; pytest --cov=sphire/bin/; coverage xml --ignore-errors
     - cd ..;
     - rm -rf build_test;
