stages:
 - test

unittest: # Name of the job
  stage: test
  image: sphiredevel/sphire-ut:eman24 # Image that should be used
  script:
     - cd ..;
     - mkdir build_test;
     - cd build_test;
     - cmake ../ -DENABLE_OPTIMIZE_MACHINE=ON;
     - make -j 8;
     - make install;
     - cd ../sphire/;
     - source activate sphire;
     - pip uninstall sphire -y;
     - python setup.py sdist; pip install dist/*.tar.gz; pip install coverage pytest pytest-cov; pytest --cov=sphire/bin/; coverage xml --ignore-errors
     - cd ../..
     - rm -r build_test
