# -*- mode: yaml -*-

name: Build conda package
on: [push]

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - CONFIG: linux
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: osx
            os: macos
          - CONFIG: win
            os: windows
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build on Linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
      shell: bash
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        ./ci_support/run_docker_build.sh

    - name: Build on macOS
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
      shell: bash
      run: |
        ./ci_support/run_osx_build.sh

    - name: Install Miniconda for windows
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        miniforge-variant: Mambaforge
      if: matrix.os == 'windows'
    - name: Build on windows
      shell: cmd
      run: |
        call activate base
        mamba.exe install -c conda-forge 'python=3.10' conda-build conda pip boa conda-forge-ci-setup=3 constructor
        if errorlevel 1 exit 1
        
        set EMAN_VERSION=2.99.54
        conda.exe mambabuild ./recipe -c cryoem -c conda-forge -c defaults
        if errorlevel 1 exit 1

        constructor ci_support/ -v --debug
        if errorlevel 1 exit
        
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
      if: matrix.os == 'windows'

    - uses: actions/upload-artifact@v3
      with:
        name: eman2.win.exe
        path: eman2.win.exe
      if: matrix.os == 'windows'

    - uses: actions/upload-artifact@v3
      with:
        name: eman2.linux.sh
        path: /home/conda/eman2.linux.sh
      if: matrix.os == 'ubuntu'

    - uses: actions/upload-artifact@v3
      with:
        name: eman2.mac.sh
        path: /Users/runner/work/eman2/eman2/eman2.mac.sh
      if: matrix.os == 'macos'
